[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.py'
exclude = '''
/(
    \.git
  | \.mypy_cache
)/
'''

[tool.isort]
multi_line_output = 3
ensure_newline_before_comments = true
line_length = 88
